version : '3.1'
services:
  bill-management-application:
    image: bill-management-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - rabbitmq
    links:
      - postgres-db
      - rabbitmq

  postgres-db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  rabbitmq:
    image: rabbitmq:3.8.3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"